# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  push:
    tags:
      - '*'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment here

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get modified directories
        id: modified-dirs
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Reference: ${{ github.ref }}"
          
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "Handling pull request"
            dirs=$(git diff --name-only -r HEAD^1 HEAD | grep -v '^\.' | grep -v '^script/' | grep -v '^appspec' | cut -d'/' -f1 | sort | uniq)
          elif [[ ${{ github.event_name }} == 'push' ]]; then
            if [[ ${{ startsWith(github.ref, 'refs/heads/') }} ]]; then
              echo "Pushed to a branch"
              dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -v '^\.' | grep -v '^script/' | grep -v '^appspec' | cut -d'/' -f1 | sort | uniq)
            elif [[ ${{ startsWith(github.ref, 'refs/tags/') }} ]]; then
              echo "Pushed to a tag"
              git tag --sort=-creatordate
              echo "current_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
              echo "Current tag: ${{ env.current_tag }}"
              previous_tag=$(git tag --sort=-creatordate | grep -A 1 ${{ env.current_tag }} | tail -n 1)
              echo "previous_tag=${previous_tag}" >> $GITHUB_ENV
              echo "Previous tag: ${{ env.previous_tag }}"
              dirs=$(git diff --name-only ${{ env.current_tag }} ${{ env.previous_tag }} | cut -d'/' -f1 | sort | uniq)
            else
              echo "Pushed to an unknown reference type"
              dirs=""
            fi
          else
            echo "Unhandled event type: ${{ github.event_name }}"
            dirs=""
          fi
      
          echo "Modified directories: ${dirs}"
      - name: List all tags
        run: git tag --sort=-creatordate

      - name: Get current tag
        id: get_current_tag
        run: echo "current_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
  
      - name: Get previous tag
        id: get_previous_tag
        run: |
          echo "current: ${{ env.current_tag}}"
          previous_tag=$(git tag --sort=-creatordate | grep -A 1 ${{ env.current_tag }} | tail -n 1)
          echo "previous_tag=${previous_tag}" >> $GITHUB_ENV
  
      - name: Output tags
        run: |
          echo "Current Tag: ${{ env.current_tag }}"
          echo "Previous Tag: ${{ env.previous_tag }}"

      - name: Check Diff
        run: |
          dirs=$(git diff --name-only ${{ env.current_tag }} ${{ env.previous_tag }} | cut -d'/' -f1 | sort | uniq)
          echo "Modified directories: ${dirs}"
