# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment here

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create PAT file
        run: echo "${{ secrets.PAT_TOKEN }}" > pat_token.txt

      - name: Verify PAT file content (optional, use with caution)
        run: cat pat_token.txt

      - name: Set PAT environment variable
        run: echo "PAT=$(cat pat_token.txt)" >> $GITHUB_ENV

      - name: Use PAT in a command
        run: |
          echo "Using the PAT in a command..."
          # Replace the following line with the actual command that uses the PAT
          echo "PAT_TOKEN is $PAT"

