# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  push:
    tags:
      - '*'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment here

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get current tag
        id: get_current_tag
        run: echo "current_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
  
      - name: Get previous tag
        id: get_prev_tag
        run: |
          # Get the current tag
          CURRENT_TAG=$(git describe --tags --abbrev=0)
  
          # Get all tags, sort them, and find the previous tag
          PREVIOUS_TAG=$(git tag --sort=-creatordate | grep -B1 $CURRENT_TAG | head -n1)
  
          # Output the previous tag
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Print previous tag
        run: echo "Previous tag is ${{ env.PREVIOUS_TAG }}"
