# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  push:
    tags:
      - '*'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment here

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check event type
        id: check_event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "This is a push event"
            echo "Ref: ${{ github.ref }}"  # Branch or tag reference
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "This is a pull request event"
            echo "PR Number: ${{ github.event.pull_request.number }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "This is a manual trigger"
          else
            echo "Unknown event"
          fi

      - name: List all tags
        run: git tag --sort=-creatordate

      - name: Get current tag
        id: get_current_tag
        run: echo "current_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
  
      - name: Get previous tag
        id: get_previous_tag
        run: |
          echo "current: ${{ env.current_tag}}"
          previous_tag=$(git tag --sort=-creatordate | grep -A 1 ${{ env.current_tag }} | tail -n 1)
          echo "previous_tag=${previous_tag}" >> $GITHUB_ENV
  
      - name: Output tags
        run: |
          echo "Current Tag: ${{ env.current_tag }}"
          echo "Previous Tag: ${{ env.previous_tag }}"
